BCDA-APS/bluesky_training

describe_instrument.ipynb
=> describe_instrument notebook can find pv_finder.py code  now

.gitignore, busy.ipynb
=> notebook describing use of busy record

bluesky/instrument/callbacks/spec_data_file_writer.py, bluesky/instrument/devices/motors.py, bluesky/instrument/framework/initialize.py, bluesky/instrument/session_logs.py
=> prefer pathlib instead of os

bluesky/instrument/callbacks/__init__.py, bluesky/instrument/epics_signal_config.py, bluesky/instrument/iconfig.yml, bluesky/instrument/queueserver.py, bluesky/instrument/queueserver_framework.py, bluesky/instrument/utils/__init__.py, bluesky/instrument/utils/reporting.py, bluesky/starter.py
=> Provision for running with queueserver

bluesky/instrument/framework/initialize.py, bluesky/instrument/iconfig.yml, bluesky/instrument/queueserver_framework.py
=> choose ophyd control layer in iconfig.yml

resources/git-help.md
Add a link to the hints for commit prefixes
=> commit message prefixes

.github/workflows/unit-tests-pytest.yml, bluesky/instrument/iconfig.yml, bluesky/instrument/session_logs.py, environment.yml
=> code from session_logs now in apstools.utils

.github/workflows/pages.yml, .gitignore, docs/Makefile, docs/make.bat, docs/requirements.txt, docs/source/conf.py, docs/source/index.rst
=> prepare Sphinx documentation

docs/source/instrument/_test_new_instrument.md, docs/source/tutor/_aps101_notes.md, docs/source/tutor/index.rst
- close #103 
For preview see: https://github.com/BCDA-APS/bluesky_training/blob/103-new-instrument-test/docs/source/instrument/_test_new_instrument.md
=> DOC #103 update test new inst

docs/source/example/_watch_temperature.ipynb, docs/source/howto/_basic_motor_scaler_scan.ipynb, docs/source/howto/_count_scaler.ipynb, docs/source/howto/_lineup_1d_peak.ipynb, docs/source/howto/_locate_image_peak.ipynb, docs/source/instrument/describe_instrument.ipynb
=> resolve nbformat id problems

.github/workflows/unit-tests-pytest.yml, README.md, bluesky/tests/test_bluesky_plans.py, bluesky/user_group_permissions.yaml, docs/source/howto/_bluesky_queueserver.md, environment.yml
=> follow upgrades in bluesky-queueserver

.github/workflows/pages.yml, .github/workflows/unit-tests-pytest.yml, docs/source/conf.py
=> Repair CI workflows

bluesky/_run_qs.sh, bluesky/qserver.sh
=> rename one of the scripts used to start the queueserver

bluesky/environments/environment_2023_2.yml
=> BUG: could not import pvaccess in new environment

docs/source/instrument/guide.md
=> replace the URL

bluesky/instrument/framework/metadata.py
=> wrap scan_id_epics with try..except

new_bluesky_instrument.py
=> also set permissions on new bluesky directory

bluesky/_run_qs.sh
=> restrict QS startup to one specific host

README.md, docs/source/index.rst
=> remove redundant content from README in favor of docs

docs/source/reference/_conda_base.md
=> replace the Miniconda installer script example

CHANGES.rst, docs/source/changes.rst, docs/source/index.rst
=> keep a history of changes between versions

docs/source/reference/_conda_base.md
=> revise Miniconda installer script - without mamba

docs/source/instrument/_install_new_instrument.rst
- close #208
I'm not convinced this PR solves the original question.  At least, it uses a more standard Sphinx way to provide the file to be downloaded.
=> use :download: role

docs/source/instrument/_install_new_instrument.rst
=> add installation checklist

.github/workflows/unit-tests-pytest.yml
- close #216
@rodolakis - Another use case for draft PR status, our CI is configured not to run on just a branch, it needs to be part of a pull request.
=> Diagnose and repair CI

CHANGES.rst, bluesky/environments/environment_2023_3.yml
=> Not yet for haven-spc package

docs/source/conf.py
=> add sphinx_tabs.tabs extension last

bluesky/instrument/framework/initialize.py, bluesky/instrument/framework/metadata.py, bluesky/instrument/iconfig.yml, bluesky/tests/test_scan_id_pv.py
=> Use RUN_ENGINE_SCAN_ID_PV if defined

bluesky/instrument/framework/metadata.py
=> add iconfig as routine diagnostic metadata

bluesky/instrument/iconfig.yml
=> add version string

CHANGES.rst, bluesky/instrument/devices/area_detector.py
=> use "zlib" as default HDF5 compression

CHANGES.rst, docs/source/changes.rst, docs/source/index.rst, new_bluesky_instrument.py
=> new_bluesky_instrument uses latest release

LICENSE.txt, bluesky/qserver.sh
=> update copyright notices to 2024

CHANGES.rst, bluesky/instrument/framework/initialize.py, bluesky/instrument/iconfig.yml
=> changes to configure new installation

CHANGES.rst, bluesky/user/quick_hello.py, docs/source/instrument/_install_new_instrument.rst, docs/source/instrument/_test_new_instrument.md
=> Cite hello world in installation checklist, generalize for queueserver

CHANGES.rst, docs/source/index.rst
=> Note on home page that bullet list are highlights.  More content is available beneath.

docs/source/reference/_create_conda_env.rst
=> redirect the broken reference
